import { faker } from '@faker-js/faker';

// ----------------------------------------------------------------------

const posts = [
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/tiro.png`,
    title: 'Ir ao Estande de Tiro',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: 'https://drive.google.com/drive/folders/1-jv2l_5NZU7xxQg9-ADH2MFvZIUidMeE',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/boliche.jpg`,
    title: 'Ir ao Boliche',
    createdAt: new Date('2023', '00', '01'),
    date: new Date('2023', '00', '29'),
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/green.png`,
    },
    finish: true,
  },

  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/acampar.jpg`,
    title: 'Acampar',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/aviao.png`,
    title: 'Viajar de Avião',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/cachoeira.jpg`,
    title: 'Ir a Cachoeira',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/cavalo.jpg`,
    title: 'Andar a Cavalo',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/comida-mexicana.png`,
    title: 'Comer Comida Mexicana',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/estadio.jpg`,
    title: 'Ir ao Estadio',
    createdAt: new Date('2022', '01', '02'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/fantasia.jpeg`,
    title: 'Ir a Festa Fantasia',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/japonesa.jpg`,
    title: 'Comer Comida Mexicana',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/praia.jpg`,
    title: 'Ir a Praia',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
  {
    id: faker.datatype.uuid(),
    cover: `/assets/images/backgrounds/zoologico.png`,
    title: 'Ir ao Zoologico',
    createdAt: new Date('2023', '00', '01'),
    date: 0,
    urlDrive: '',
    comment: faker.datatype.number(),
    share: faker.datatype.number(),
    favorite: faker.datatype.number(),
    author: {
      name: faker.name.fullName(),
      avatarUrl: `/assets/images/avatars/red.png`,
    },
    finish: false,
  },
];

export default posts;
